### ISSUE TITLE
lack of support & proper testing 

### ISSUE THREAD

**Issue by fnicholas** [airbnb/smartstack-cookbook#18]
The lack of support from the author of this cookbook is just sad. Doc is poorly written. Poor testing. It would be a good idea to simplify the testing of this cookbook. 

e.g:
node 1 - synapse
node 2 - nerve
node 3 - zookeeper 

then apply your test "helloworld" service & then check haproxy for status & processed request. 

Comparing the current work/testing here, Consul by HashiCorp is looking attractive. Why? 

Good documentation. 
Good support. 
Good testing. 

Hopefully the author of smartstack cookbook will do something about this.

**Comment by jolynch** [comment]
@fnicholas I'm not sure what you hope to achieve from this issue. Pull requests or forking are always options for you if you're unhappy with the code.

I don't work on the smartstack cookbook, but I do help maintain synapse/nerve and we've received similar feedback there. I think the reality is that SmartStack is a system that Airbnb and Yelp help maintain because we use it, but open source doesn't mean free lunch.

I know that I do most of my work on SmartStack outside working hours, on my own free time, and my understanding is that Igor does this as well. Contrast that with HashiCorp where service discovery is their core competency and they make money from it...

**Comment by igor47** [comment]
this cookbook has drifted pretty far from our internal version of it at airbnb. backporting changes between a private and a public repo is kind of a pain. i'm tempted to delete this project off github. i might just clearly mark the README as deprecated...

**Comment by fnicholas** [comment]
sounds good. i suggest it should be deleted.
